### ISSUE TITLE
Enhancement: SilverStripe 4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-controllerpolicy#15]
This is a placeholder issue for SS4 compatibility.

## Pre-requisites

- [x] Branch current `master` off to `1` or similar for maintaining the current version
- [x] Update/add composer branch alias to `2.0.x-dev`

## Requirements

- [x] PSR-2 code formatting (done - thanks @helpfulrobot!)
- [x] Add namespacing for module including [upgrader](https://github.com/silverstripe/silverstripe-upgrader) mapping file
- [x] Implement core namespaces, update configuration (including CI builds), tests and template locations
- [x] Add PSR-4 autoloader (inc. move `code/` to `src/` for consistency)
- [x] Update documentation

## Implications

* Minimum PHP version becomes 5.6

**Comment by be2n** [comment]
@robbieaverill is this issue still relevant?

**Comment by robbieaverill** [comment]
PR at #18
